# numpy Operations

In [3]:
import numpy as np
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [6]:
x + y #addition
x - y #subtraction
x * 2 #multiplication
x ** 2 #exponentiation
x.dot(y) #dot product
x.T #transpose
x.dtype #datatype
x.astype #change type as 

<function ndarray.astype>

## Indexing and Slicing

In [24]:
a = np.arange(13)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [22]:
a[0], a[1], a[1:4]

(0, 1, array([1, 2, 3]))

In [30]:
a[-5::2] # slice from last fifth element towards end counting 2
a[-5::-3] # slice from last fifth element towards end counting backwards 3

array([8, 5, 2])

In [33]:
b = np.arange(1,36)
b.resize(6, 6)

In [34]:
b

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35,  0]])

In [38]:
b[2, 3]   # particular cell
b[2, 2:4] # particular slice

array([15, 16])

In [43]:
b[2::2, 0:2]

array([[13, 14],
       [25, 26]])

In [46]:
b[b>30] = 30 #capping maximum element to as 30

In [48]:
b1 = b[:3, :3]

In [49]:
b1

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15]])

In [50]:
b2 = b[3:, 3:]
b2

array([[22, 23, 24],
       [28, 29, 30],
       [30, 30,  0]])

In [51]:
b2[:] = 0


In [54]:
c = b.copy()

In [57]:
b2 = b[:3, :3]
b2[:] = 0

In [58]:
c

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21,  0,  0,  0],
       [25, 26, 27,  0,  0,  0],
       [30, 30, 30,  0,  0,  0]])

In [59]:
b

array([[ 0,  0,  0,  4,  5,  6],
       [ 0,  0,  0, 10, 11, 12],
       [ 0,  0,  0, 16, 17, 18],
       [19, 20, 21,  0,  0,  0],
       [25, 26, 27,  0,  0,  0],
       [30, 30, 30,  0,  0,  0]])

### Iterate over Arrays

In [60]:
itr = np.random.randint(0, 10, (4, 3))

In [61]:
itr

array([[0, 4, 6],
       [3, 6, 4],
       [3, 1, 9],
       [8, 4, 0]])

In [63]:
for row in itr:
    print(row)

[0 4 6]
[3 6 4]
[3 1 9]
[8 4 0]


In [65]:
for i, row in enumerate(itr):
    print('row', i, 'is' , row)

row 0 is [0 4 6]
row 1 is [3 6 4]
row 2 is [3 1 9]
row 3 is [8 4 0]


In [67]:
l = [1, 2, 3, 4]
for i, va in enumerate(l):
    print('index', i, 'is of value', va)

index 0 is of value 1
index 1 is of value 2
index 2 is of value 3
index 3 is of value 4


In [68]:
itr = itr**2

In [69]:
itr

array([[ 0, 16, 36],
       [ 9, 36, 16],
       [ 9,  1, 81],
       [64, 16,  0]])

In [70]:
itr3 = np.random.randint(0, 10, (4, 3))

In [73]:
for i, j in zip(itr, itr3):
    print(i, '+', j , '=', i+j)

[ 0 16 36] + [3 0 6] = [ 3 16 42]
[ 9 36 16] + [4 0 5] = [13 36 21]
[ 9  1 81] + [1 7 6] = [10  8 87]
[64 16  0] + [8 4 6] = [72 20  6]


In [74]:
['a', 'b'] + [1, 2]

['a', 'b', 1, 2]

In [75]:
itr[:, ::1]

array([[ 0, 16, 36],
       [ 9, 36, 16],
       [ 9,  1, 81],
       [64, 16,  0]])

In [76]:
itr[::4]

array([[ 0, 16, 36]])

In [77]:
itr

array([[ 0, 16, 36],
       [ 9, 36, 16],
       [ 9,  1, 81],
       [64, 16,  0]])

In [82]:
itr.reshape(12)[::4]

array([ 0, 36, 81])

In [83]:
itr

array([[ 0, 16, 36],
       [ 9, 36, 16],
       [ 9,  1, 81],
       [64, 16,  0]])